spring.application.name=commarce
server.port=8000
coach.name=Sad Bin Siddique

# Log level configuration
#logging.level.org.springframework=DBUG
#logging.level.hibernate=TRACE

# Database configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/commarce_db
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Context path of the application
server.servlet.context-path=/v1

# Default HTTPS session timeout (minutes = m, hours = h, days = d)
#server.servlet.session.timeout=5m

# Endpoint to include
#management.endpoints.web.exposure.include=health,info

# Endpoint to exclude
#management.endpoints.web.exposure.exclude=env,beans

# Set base path for actuator endpoints
#management.endpoints.web.base-path=/actuator

spring.main.lazy-initialization=true

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/student_tracker?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true


# Turn off the spring boot banner
spring.main.banner-mode=off

# Reduce logging level  set logging level to warn
logging.level.root=warn